/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: test_msgs/AddTwoIntsServiceRequest
 */

package id.jrosmessages.test_msgs;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;

// user defined imports
import java.io.IOException;
import java.util.*;

/**
 * Definition for test_msgs/AddTwoIntsServiceRequest
 */
@MessageMetadata(
    name = AddTwoIntsRequestMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "a", "b" }
)
public class AddTwoIntsRequestMessage implements Message {
   
   static final String NAME = "test_msgs/AddTwoIntsServiceRequest";

   public long a;
   
   public long b;
   
   public AddTwoIntsRequestMessage withA(long a) {
       this.a = a;
       return this;
   }
   
   public AddTwoIntsRequestMessage withB(long b) {
       this.b = b;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           a,
           b
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof AddTwoIntsRequestMessage other)
           return
               a == other.a &&
               b == other.b
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "a", a,
           "b", b
       );
   }
   
}
