/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Message class for jrosclient
 * 
 * Generated for ROS msg file: test_msgs/GoalID
 */

package id.jrosmessages.test_msgs;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.primitives.Time;
import id.jrosmessages.std_msgs.StringMessage;

/**
 * Definition for test_msgs/GoalID
 */
@MessageMetadata(
    name = GoalIDMessage.NAME,
    fields = { "stamp", "id" },
    md5sum = "240a3309d52227ee0745a03a208f9de9"
)
public class GoalIDMessage implements Message {
   
   static final String NAME = "test_msgs/GoalID";

   /**
    * The stamp should store the time at which this goal was requested.
    * It is used by an action server when it tries to preempt all
    * goals that were requested before a certain time
    */
   public Time stamp = new Time();
   
   /**
    * The id provides a way to associate feedback and
    * result message with specific goal requests. The id
    * specified must be unique.
    */
   public StringMessage id = new StringMessage();
   
   public GoalIDMessage withStamp(Time stamp) {
       this.stamp = stamp;
       return this;
   }
   
   public GoalIDMessage withId(StringMessage id) {
       this.id = id;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           stamp,
           id
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       var other = (GoalIDMessage) obj;
       return
           Objects.equals(stamp, other.stamp) &&
           Objects.equals(id, other.id)
       ;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "stamp", stamp,
           "id", id
       );
   }
   
}
